# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Science Together
email: scitog@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Science together in an online world - which tools help you to
  success and which rules you need to follow.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://sciencetogether.github.io/" # the base hostname & protocol for your site
twitter_username: SciTog
github_username:  sciencetogether
#permalink: /tools/:title.html
# Build settings
markdown: kramdown
collections:
  tools:
    output: true
defaults:
  - scope:
      path: ""
      type: tools
    values:
      layout: tool
exclude:
  - _tools/template._md
